### ISSUE TITLE
IPS_Patch_Creator_1.5.4-2 with new firmware 15.0.0

### ISSUE THREAD

**Issue by oresterosso75** [mrdude2478/IPS_Patch_Creator#1]
this with new firmware 15.0.0 not work!,need a new update?

![Cattura](https://user-images.githubusercontent.com/50875656/195148271-cb2092c0-839d-49fa-964e-a16f792179af.PNG)

**Comment by mrdude2478** [comment]
You will need to update your keys with key 0E to be able to decrypt files. Wait until lockpic rcm gets updated.

**Comment by AMSNX** [comment]
no working in FS patches, loader and ES all good

**Comment by oresterosso75** [comment]
> no working in FS patches, loader and ES all good

so if no patch work FS, you have to wait for an update ..?
forgive me but I did not understand the meaning of the answer.
