### ISSUE TITLE
hachtool-mod.zip

### ISSUE THREAD

**Issue by oresterosso75** [mrdude2478/IPS_Patch_Creator#12]
Good evening, first of all I wanted to thank you for the work you have done.
I wanted to ask you a question, I hope it's not stupid and that you will understand.
I noticed a folder within the project with the name hachtool-mod.zip
I wanted to understand how I should use the files inside, is this a separate project that needs to be compiled?
Could you kindly explain to me how to do it?

**Comment by mrdude2478** [comment]
It's for an older version of hactool, don't worry about it. I will remove it soon from the git.
