### ISSUE TITLE
NFIM Patches Not Able To Decrypt

### ISSUE THREAD

**Issue by SeaMooseD** [mrdude2478/IPS_Patch_Creator#13]
Hey not sure if this belongs in Issue #8 since it deals with FW 17, but that also seems to be more for FS patches so I'm creating a new issue. Please correct me if this is the wrong step. However, the issue is that I can't create NFIM patches for my switch. I have downloaded the firmware as well as dumped my keys, but it doesn't matter whether I rename the prod.keys file to keys.dat or fill in the template manually. I get the same error: "Unable to decrypt, did you update your keys? Try adjusting the NFIM size limits in the config settings if firmware is greater than 15.0.0.". I downloaded the latest version of the project from releases so I know it's not a compatibility issue, and it doesn't matter what I change the size limits to I can never get past this error message. I have tried finding an answer via searching the web and looking through the issues here, but I don't seem to really understand what's going on. I did make sure to use the newest version of lockpick (1.9.11), and am still getting these errors.

**Comment by mrdude2478** [comment]
It all works fine for me, so either your hactool has not been updated or you don't have the correct keys installed.
