### ISSUE TITLE
on fresh clone of repo, if you don't have tools folder in current working directory, tool crashes

### ISSUE THREAD

**Issue by shayaantx** [mrdude2478/IPS_Patch_Creator#6]
I just ran a fresh clone in debug mode from visual studio 2022 and it kept crashing due to a missing tools folder

I just put below code in Program.cs to make it work, but probably makes sense in some helper function to when you call SQLiteConnection.CreateFile(mydb); for various databases.

```
System.IO.Directory.CreateDirectory("./tools");
```

Just thought I'd mention it, I can throw up a PR to fix if you want

**Comment by mrdude2478** [comment]
Fixed, thanks for reporting.
