### ISSUE TITLE
fs_patches not compatible with 17.0.0

### ISSUE THREAD

**Issue by AMSNX** [mrdude2478/IPS_Patch_Creator#8]
![image](https://github.com/mrdude2478/IPS_Patch_Creator/assets/102128616/19614f44-c77e-47aa-8948-fef8ae920963)

keys already updated, only fs can't be decripted

**Comment by ELCALLEJONGAMER** [comment]
Did you have problems with the  ES patches?

![image](https://github.com/mrdude2478/IPS_Patch_Creator/assets/57427897/cd5d458f-0349-4f9d-9b89-9327f759d8dc)

**Comment by AMSNX** [comment]
no, only FS

**Comment by ELCALLEJONGAMER** [comment]
> no, only FS

Would I have done something different? I extracted the firmware with tegraexplorer and the keys with lockpick

**Comment by mrdude2478** [comment]
First of all you need to compile the new hactool version to be able to extract FS kip files, even then FS files have changed so new patterns need to be added to the program to find one of the locations to patch, so for now you won't be able to ply installed xci files or use NRO forwarders until this has been done. I'll updated program once the new locations for the FS patches are known. In the meantime, you can still play installed nsp files with es patches.

**Comment by BitterSweetcandyshop** [comment]
Where would I be able to follow the progress on the other patchetheir there a discord?

**Comment by oresterosso75** [comment]
unfortunately I confirm the impossibility of creating FS patches.
What problems does this cause?

**Comment by ELCALLEJONGAMER** [comment]
> Firmware 17.0.0 unfortunately I confirm the impossibility of creating FS patches. What problems does this cause?

New encryption keys

**Comment by BeckysFootSlave** [comment]
> First of all you need to compile the new hactool version to be able to extract FS kip files, even then FS files have changed so new patterns need to be added to the program to find one of the locations to patch, so for now you won't be able to play installed xci files or use NRO forwarders until this has been done. I'll updated program once the new locations for the FS patches are known. In the meantime, you can still play installed nsp files with es patches.

Dear mrdude,

How to compile hactool? I'm getting completly crazy over here and can't find out what the heck I am missing!?

If I use the hactool.exe inside your App (182kb) with the new keys from 17.0.0 I can create the patches for Loader, ES and NFIM

If I clone fresh hactool.git from SciersM with the newest changes I get some warnings and a hactool.exe with 475kb. (Also had one with over 800kb)

Using MSYS2-MINGW64 because MSYS2 crashes always with ERROR2!

But if I use my compiled hactool.exe with your Tool I always get dec-Loader.bin not found no matter what I do or how I compile it!

Just asking If you could kick my stupid brain into the right place to see or read waht I have to do!

Best regards and greetings from Germany! (Sorry for disturbing you!)

**Comment by mrdude2478** [comment]
> > First of all you need to compile the new hactool version to be able to extract FS kip files, even then FS files have changed so new patterns need to be added to the program to find one of the locations to patch, so for now you won't be able to play installed xci files or use NRO forwarders until this has been done. I'll updated program once the new locations for the FS patches are known. In the meantime, you can still play installed nsp files with es patches.
> 
> Dear mrdude,
> 
> How to compile hactool? I'm getting completly crazy over here and can't find out what the heck I am missing!?
> 
> If I use the hactool.exe inside your App (182kb) with the new keys from 17.0.0 I can create the patches for Loader EDIT: ES and NFIM giving error
> 
> If I clone fresh hactool.git from SciresM with the newest changes I get some warnings and a hactool.exe with 475kb. (Also had one with over 800kb)
> 
> Using MSYS2-MINGW64 because MSYS2 crashes always with ERROR2!
> 
> But if I use my compiled hactool.exe with your Tool I always get dec-Loader.bin not found no matter what I do or how I compile it! ES and NFIM say: Input string has the wrong format!
> 
> Just asking If you could kick my stupid brain into the right place to see or read waht I have to do!
> 
> Best regards and greetings from Germany! (Sorry for disturbing you!)

Just get the new source from hactool git and compile it, it compiles fine on both windows and linux.

**Comment by Cmartin13** [comment]
> Just get the new source from hactool git and compile it, it compiles fine on both windows and linux. Don't use the mods I posted - these are for before hactool git was updated.

Hello MrDude,
First of all, hats off to you for creating such a convenient utility!

After a buttload of head scratching and debugging your code in VS, I finally managed to generate FS patches for firmware 17.0.0!

![image](https://github.com/mrdude2478/IPS_Patch_Creator/assets/22663453/bf472f48-5ac8-47dc-b454-1e6e984c2af5)

Here's the trick:
- Latest prod.keys file is necessary. Dumped with LockPick_RCM v1.9.11 (Latest version I am aware of).
- Using the latest release of hactool does not work. You need to compile the code from his latest commit. Also don't use the hactool mods provided here as they are not needed anymore and will not work.
- You need to compile IPS_Patch_Creator using the latest commit in Visual Studio. HOWEVER, for some reason SciresM removed the "--disableoutput" argument from hactool in his latest commit. I had to edit the main.cs file and remove every instance where hactool is called using this argument on lines 597, 1607, 1643, 1773, 3042, 3093, 3113, 3959 and 4004.

Here's the resulting main.cs and up to date compiled hactool.exe files if you're interested. I Tested the Loader, ES, ES2, FS and NFIM tabs and they all worked without any errors. I haven't tested if the patches themselves work on the Switch CFW though.

[Main_patched.zip](https://github.com/mrdude2478/IPS_Patch_Creator/files/13065664/Main_patched.zip)
[hactool.zip](https://github.com/mrdude2478/IPS_Patch_Creator/files/13065666/hactool.zip)

Hope it helps!
Cheers!

**Comment by fecent** [comment]
> > Just get the new source from hactool git and compile it, it compiles fine on both windows and linux. Don't use the mods I posted - these are for before hactool git was updated.
> 
> Hello MrDude, First of all, hats off to you for creating such a convenient utility!
> 
> After a buttload of head scratching and debugging your code in VS, I finally managed to generate FS patches for firmware 17.0.0!
> 
> ![image](https://user-images.githubusercontent.com/22663453/277213158-bf472f48-5ac8-47dc-b454-1e6e984c2af5.png)
> 
> Here's the trick:
> 
> * Latest prod.keys file is necessary. Dumped with LockPick_RCM v1.9.11 (Latest version I am aware of).
> * Using the latest release of hactool does not work. You need to compile the code from his latest commit. Also don't use the hactool mods provided here as they are not needed anymore and will not work.
> * You need to compile IPS_Patch_Creator using the latest commit in Visual Studio. HOWEVER, for some reason SciresM removed the "--disableoutput" argument from hactool in his latest commit. I had to edit the main.cs file and remove every instance where hactool is called using this argument on lines 597, 1607, 1643, 1773, 3042, 3093, 3113, 3959 and 4004.
> 
> Here's the resulting main.cs and up to date compiled hactool.exe files if you're interested. I Tested the Loader, ES, ES2, FS and NFIM tabs and they all worked without any errors. I haven't tested if the patches themselves work on the Switch CFW though.
> 
> [Main_patched.zip](https://github.com/mrdude2478/IPS_Patch_Creator/files/13065664/Main_patched.zip) [hactool.zip](https://github.com/mrdude2478/IPS_Patch_Creator/files/13065666/hactool.zip)
> 
> Hope it helps! Cheers!

Your hactool is not working. Are you sure you have tested it?

**Comment by ps3120** [comment]
I used hactoolnet for generate fs but on cfw not work

**Comment by ps3120** [comment]
I tested with new hactool and after generate patch not work on cfw, i think offset in ips patch creator are wrong

**Comment by Cmartin13** [comment]
> Your hactool is not working. Are you sure you have tested it?

Yes I did. I just redownloaded the hactool I posted and tried it again. What doesn't work for you?

**Comment by ps3120** [comment]
Fs patch not work

**Comment by Cmartin13** [comment]
> Fs patch not work

Did you rebuild IPS_Patch_Creator using the main.cs file I provided?

**Comment by ps3120** [comment]
Fs patch not work

**Comment by ps3120** [comment]
Yes, i generated fs patch but on cfw not work

**Comment by ps3120** [comment]
Or problem is loader

**Comment by fecent** [comment]
> > Your hactool is not working. Are you sure you have tested it?
> 
> Yes I did. I just redownloaded the hactool I posted and tried it again. What doesn't work for you?

I will place your hactool.exe in the tools directory, and make patch will prompt "Error is: The format of the input string is incorrect" after selecting the firmware

**Comment by Cmartin13** [comment]
> I will place your hactool.exe in the tools directory, and make patch will prompt "Error is: The format of the input string is incorrect" after selecting the firmware

Yes this is the error I got too before modifying the main.cs file for IPS_Patch_Creator. You need to rebuild it with Visual Studio or it will not work with the new hactool.

**Comment by oresterosso75** [comment]
> > Metterò il tuo hactool.exe nella directory degli strumenti e la patch richiederà "L'errore è: il formato della stringa di input non è corretto" dopo aver selezionato il firmware
> 
> Sì, questo è l'errore che ho ricevuto anch'io prima di modificare il file main.cs per IPS_Patch_Creator. È necessario ricostruirlo con Visual Studio altrimenti non funzionerà con il nuovo hactool.

I recompiled with your files and this is the result:
it does not work
![IMG_20231023_153408_976](https://github.com/mrdude2478/IPS_Patch_Creator/assets/50875656/f58dfd5c-1c9c-44de-b78e-72ba0a08ab66)

**Comment by fecent** [comment]
> > I will place your hactool.exe in the tools directory, and make patch will prompt "Error is: The format of the input string is incorrect" after selecting the firmware
> 
> Yes this is the error I got too before modifying the main.cs file for IPS_Patch_Creator. You need to rebuild it with Visual Studio or it will not work with the new hactool.

I have compiled the latest source code using VS.2022, but there is no tools folder after compilation. I used the previous tools folder and replaced your hactool. Is there an error in my compilation?

**Comment by Cmartin13** [comment]
> > > I will place your hactool.exe in the tools directory, and make patch will prompt "Error is: The format of the input string is incorrect" after selecting the firmware
> > 
> > 
> > Yes this is the error I got too before modifying the main.cs file for IPS_Patch_Creator. You need to rebuild it with Visual Studio or it will not work with the new hactool.
> 
> I have compiled the latest source code using VS.2022, but there is no tools folder after compilation. I used the previous tools folder and replaced your hactool. Is there an error in my compilation?

Like I said, I only managed to get IPS_Patch_Creator to work with hactool and generate IPS files without error.
I have very little knowledge on how sigpatches operate, and haven't tested them on CFW yet.

**Comment by ps3120** [comment]
It worked for me too without errors but the sigpatches don't work on cfw

**Comment by fecent** [comment]
> > > > 我将你的hactool.exe放在tools目录下，选择固件后make patch会提示“错误是：输入字符串的格式不正确”
> > > 
> > > 
> > > 是的，这也是我在修改 IPS_Patch_Creator 的 main.cs 文件之前遇到的错误。您需要使用 Visual Studio 重建它，否则它将无法与新的 hactool 一起使用。
> > 
> > 
> > 我用VS.2022编译了最新的源码，但是编译后没有tools文件夹。我使用了之前的tools文件夹并替换了你的hactool。我的编译有错误吗？
> 
> 就像我说的，我只是设法让 IPS_Patch_Creator 与 hactool 一起工作并生成 IPS 文件而没有错误。 我对 sigpatches 的运作方式知之甚少，也没有在 CFW 上测试过它们。



> > > > I will place your hactool.exe in the tools directory, and make patch will prompt "Error is: The format of the input string is incorrect" after selecting the firmware
> > > 
> > > 
> > > Yes this is the error I got too before modifying the main.cs file for IPS_Patch_Creator. You need to rebuild it with Visual Studio or it will not work with the new hactool.
> > 
> > 
> > I have compiled the latest source code using VS.2022, but there is no tools folder after compilation. I used the previous tools folder and replaced your hactool. Is there an error in my compilation?
> 
> Like I said, I only managed to get IPS_Patch_Creator to work with hactool and generate IPS files without error. I have very little knowledge on how sigpatches operate, and haven't tested them on CFW yet.

I am unable to generate ips, possibly due to compilation issues. When I switch back to the old hactool, I can generate 16.1.0 ips

**Comment by mrdude2478** [comment]
[hactool.zip](https://github.com/mrdude2478/IPS_Patch_Creator/files/13079677/hactool.zip)

For those trying to generate patches for FW17.0.0, patches aren't complete yet (nobody claimed they were), we still need to add patching for nro forwarders and for xci/nro that have a moddified nca header. XCI works if you use tinwoo 1.24 to install:

https://gbatemp.net/threads/tinwoo-installer.579661/page-15#post-10272039

Also I Have attached a windows version of hactool that I modded myself, so I know it works.

**Comment by BeckysFootSlave** [comment]
@mrdude2478 

If I use your newly provided hactool.exe it dosn't work for me!

Using your IPS_Patch_Creator_1.5.6-5 and package3 I get two systemerrors from hactool.exe:
1. telling me sys-2.0.dll not found
2. msys-gcc_s-seh-1.dell not found

Then IPS Patch Creator gives me an error that dec-loader.bin couldn't be found/is missing

If I use the compiled Version (you were right with wrong FluentFTP Version) I don't get the errors from that hactool.exe but I get the error from The Patcher also telling me that dec-loader.bin is missing!

If I use the hactool.exe from @Cmartin13 and a compiled Version, including his changed main.cs, of IPS Patch Creator I get no errors!

If I am a complete dumb moron then just say it, no problem!
Maybe I fu... up my system over here, who knows!

Just wanted to let you know that bc any info you all awesome people working on that could get helps I hope?!

**Comment by mrdude2478** [comment]
> @mrdude2478
> 
> If I use your newly provided hactool.exe it dosn't work for me!
> 
> Using your IPS_Patch_Creator_1.5.6-5 and package3 I get two systemerrors from hactool.exe:
> 
> 1. telling me sys-2.0.dll not found
> 2. msys-gcc_s-seh-1.dll not found
> 
> Then IPS Patch Creator gives me an error that dec-loader.bin couldn't be found/is missing
> 
> If I use the compiled Version (you were right with wrong FluentFTP Version) I don't get the errors from that hactool.exe but I get the error from The Patcher also telling me that dec-loader.bin is missing!
> 
> If I use the hactool.exe from @Cmartin13 and a compiled Version, including his changed main.cs, of IPS Patch Creator I get no errors!
> 
> If I am a complete dumb moron then just say it, no problem! Maybe I fu... up my system over here, who knows!
> 
> Just wanted to let you know that bc any info you all awesome people working on that could get helps I hope?!

I used msys2 on windows so I already have those dll's installed, I'll compile on linux later with x86 toolchain and post that, that should solve the issues with the dll's that are missing.

**Comment by fecent** [comment]
> [hactool.zip](https://github.com/mrdude2478/IPS_Patch_Creator/files/13079677/hactool.zip)
> 
> For those trying to generate patches for FW17.0.0, patches aren't complete yet (nobody claimed they were), we still need to add patching for nro forwarders and for xci/nro that have a moddified nca header. XCI works if you use tinwoo 1.24 to install:
> 
> https://gbatemp.net/threads/tinwoo-installer.579661/page-15#post-10272039
> 
> Also I Have attached a windows version of hactool that I modded myself, so I know it works. Also I suggest you keep an eye on this for patch info.
> 
> [ITotalJustice/sys-patch#5](https://github.com/ITotalJustice/sys-patch/issues/5)

Thank you for your dedication to this project

**Comment by ITotalJustice** [comment]
> [hactool.zip](https://github.com/mrdude2478/IPS_Patch_Creator/files/13079677/hactool.zip)
> 
> For those trying to generate patches for FW17.0.0, patches aren't complete yet (nobody claimed they were), we still need to add patching for nro forwarders and for xci/nro that have a moddified nca header. XCI works if you use tinwoo 1.24 to install:
> 
> https://gbatemp.net/threads/tinwoo-installer.579661/page-15#post-10272039
> 
> Also I Have attached a windows version of hactool that I modded myself, so I know it works. Also I suggest you keep an eye on this for patch info.
> 
> [ITotalJustice/sys-patch#5](https://github.com/ITotalJustice/sys-patch/issues/5)

Hi, i thought that I should mention that not modifying the distribution bit does break some things.

You can install the base game without modifying anything, and it will work fine.

Installing the base game unmodified + an update will cause the game to crash when starting.

This isn't limited to fw 17, it's the same on 16 and likely on all earlier fw versions, although I haven't tested this. 

So while it's nice to have the option to not modify the header, it's not a good idea to have it as the default, at least for now anyway :)

**Comment by THZoria** [comment]
Would it be possible to detect the firmware and set the distribution bit automatically ?

**Comment by mrdude2478** [comment]
> Would it be possible to detect the firmware and set the distribution bit automatically ?

That would break the ability to select it as an option, so no.

**Comment by mrdude2478** [comment]
Update complete for fw 17.0.0, new release in release page.

**Comment by oresterosso75** [comment]
> Aggiornamento completato per fw 17.0.0, nuova release nella pagina release.

thanks 🙏
