### ISSUE TITLE
Unable to decrypt whit updated keys SOLVED

### ISSUE THREAD

**Issue by ELCALLEJONGAMER** [mrdude2478/IPS_Patch_Creator#9]
Try to create the ES patches whit this error

![Captura de pantalla 2023-10-12 131543](https://github.com/mrdude2478/IPS_Patch_Creator/assets/57427897/267efeef-776f-4df2-b403-477f1ce8ee82)

Unable to decrypt, did you update your keys?

Try adjusting the ES size limits in the config settings if firmware is greater than 15.0.0.

UPDATE:

Solved, you have to extract the keys with the new lockpick_rcm, apparently I had an old one.

Now this is the problem
![image](https://github.com/mrdude2478/IPS_Patch_Creator/assets/57427897/a88d21bb-bfdf-45b3-a422-c8fc193f99e7)

![image](https://github.com/mrdude2478/IPS_Patch_Creator/assets/57427897/6219b861-213d-4db8-8913-917dc7de4d36)

**Comment by AMSNX** [comment]
your keys is not updated, only FS pacth won't decrypt at moment

**Comment by ELCALLEJONGAMER** [comment]
> your keys is not updated, only FS pacth won't decrypt at moment

Thank u!

**Comment by AMSNX** [comment]
you make fs pacthes? how u can send link please

**Comment by impeeza** [comment]
Duplicated to #8 please close this and add any relevant information to it.
